lb1_initial_angle: 84.
lb2_initial_angle: 47.
lb3_initial_angle: 48.
lf1_initial_angle: 85.
lf2_initial_angle: 34.
lf3_initial_angle: 28.
rb1_initial_angle: 85.
rb2_initial_angle: 140.
rb3_initial_angle: 137.
rf1_initial_angle: 80.
rf2_initial_angle: 139.
rf3_initial_angle: 141.